---
# Source: secret/templates/external-secret.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: eden-worker-celery-broker-url
spec:
  secretStoreRef:
    kind: SecretStore
    name: doppler-eden-worker
  target:
    name: eden-worker-celery-broker-url
  data:
    - secretKey: CELERY_BROKER_URL
      remoteRef:
        key: CELERY_BROKER_URL
---
# Source: secret/templates/external-secret.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: eden-worker-celery-result-backend
spec:
  secretStoreRef:
    kind: SecretStore
    name: doppler-eden-worker
  target:
    name: eden-worker-celery-result-backend
  data:
    - secretKey: CELERY_RESULT_BACKEND
      remoteRef:
        key: CELERY_RESULT_BACKEND
