---
# Source: deployment/templates/external-secret.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: heimdall-svc-django-secret
spec:
  secretStoreRef:
    kind: SecretStore
    name: doppler-heimdall-svc
  target:
    name: heimdall-svc-django-secret
  data:
    - secretKey: DJANGO_SECRET
      remoteRef:
        key: DJANGO_SECRET
