---
# Source: deployment/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: socrates-svc
  labels:
    helm.sh/chart: deployment-0.1.0
    app.kubernetes.io/name: socrates-svc
    app.kubernetes.io/instance: socrates-deployment
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: socrates-svc
      app.kubernetes.io/instance: socrates-deployment
  template:
    metadata:
      labels:
        helm.sh/chart: deployment-0.1.0
        app.kubernetes.io/name: socrates-svc
        app.kubernetes.io/instance: socrates-deployment
        app.kubernetes.io/managed-by: Helm
    spec:
      securityContext:
        {}
      containers:
        - name: socrates-svc
          securityContext:
            {}
          image: "ewr.vultrcr.com/polytlk/socrates:sha-045c15a"
          ports:
            - containerPort: 8079
              protocol: TCP
          env:
            - name: OPENAI_API_KEY
              value: sk-svcacct-2GwbN26du2TEyZV2g0KhB675kkCRoE_bPw6mi6Yh88f0O_HQ3lhekoJrs7C0zufcr3TT3BlbkFJd-PcoO7N0bF6FfMTXrGjTsjxgTpKVPvSE8lsjdHwOoBEu9wVXDOZx0o8BBrdyAnkbswA
            - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
              value: http://opentelemetry-collector.opentelemetry.svc.cluster.local/v1/traces
            - name: ENVIRONMENT
              value: development
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8079
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readiness
              port: 8079
            initialDelaySeconds: 5
            periodSeconds: 10
