---
# Source: deployment/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: eden-svc
  labels:
    helm.sh/chart: deployment-0.1.0
    app.kubernetes.io/name: eden-svc
    app.kubernetes.io/instance: eden-deployment
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 7079
      targetPort: 7079
      protocol: TCP
  selector:
    app.kubernetes.io/name: eden-svc
    app.kubernetes.io/instance: eden-deployment
