---
# Source: deployment/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eden-svc
  labels:
    helm.sh/chart: deployment-0.1.0
    app.kubernetes.io/name: eden-svc
    app.kubernetes.io/instance: eden-deployment
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: eden-svc
      app.kubernetes.io/instance: eden-deployment
  template:
    metadata:
      labels:
        helm.sh/chart: deployment-0.1.0
        app.kubernetes.io/name: eden-svc
        app.kubernetes.io/instance: eden-deployment
        app.kubernetes.io/managed-by: Helm
    spec:
      securityContext:
        {}
      containers:
        - name: eden-svc
          securityContext:
            {}
          image: "ewr.vultrcr.com/polytlk/eden:sha-5e3ec4f"
          ports:
            - containerPort: 7079
              protocol: TCP
          env:
            - name: CELERY_BROKER_URL
              valueFrom:
                secretKeyRef:
                  key: CELERY_BROKER_URL
                  name: eden-svc-celery-broker-url
            - name: CELERY_RESULT_BACKEND
              valueFrom:
                secretKeyRef:
                  key: CELERY_RESULT_BACKEND
                  name: eden-svc-celery-result-backend
            - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
              value: http://opentelemetry-collector.otel-collector.svc.cluster.local/v1/traces
            - name: ENVIRONMENT
              value: development
          livenessProbe:
            httpGet:
              path: /healthz
              port: 7079
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readiness
              port: 7079
            initialDelaySeconds: 5
            periodSeconds: 10
