---
# Source: secret/templates/external-secret.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: otel-collector-secrets-honeycomb-api-key
spec:
  secretStoreRef:
    kind: SecretStore
    name: doppler-otel-collector-secrets
  target:
    name: otel-collector-secrets-honeycomb-api-key
  data:
    - secretKey: HONEYCOMB_API_KEY
      remoteRef:
        key: HONEYCOMB_API_KEY
