---
# Source: secret/templates/external-secret.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tyk-operator-secrets-tyk-operator-conf
spec:
  secretStoreRef:
    kind: SecretStore
    name: doppler-tyk-operator-secrets
  target:
    name: tyk-operator-secrets-tyk-operator-conf
  data:
    - secretKey: TYK_OPERATOR_CONF
      remoteRef:
        key: TYK_OPERATOR_CONF
