---
# Source: secret/templates/json-external-secret.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tyk-operator-secrets-tyk-operator-conf
spec:
  secretStoreRef:
    kind: SecretStore
    name: doppler-tyk-operator-secrets
  target:
    name: tyk-operator-secrets-tyk-operator-conf
  dataFrom:
  - extract:
      key: TYK_OPERATOR_CONF
