---
# Source: deployment/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: socrates-svc
  labels:
    helm.sh/chart: deployment-0.1.0
    app.kubernetes.io/name: socrates-svc
    app.kubernetes.io/instance: socrates-deployment
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 8079
      targetPort: 8079
      protocol: TCP
  selector:
    app.kubernetes.io/name: socrates-svc
    app.kubernetes.io/instance: socrates-deployment
