---
# Source: secret/templates/external-secret.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: heimdall-svc-django-secret
spec:
  secretStoreRef:
    kind: SecretStore
    name: doppler-heimdall-svc
  target:
    name: heimdall-svc-django-secret
  data:
    - secretKey: DJANGO_SECRET
      remoteRef:
        key: DJANGO_SECRET
---
# Source: secret/templates/external-secret.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: heimdall-svc-tyk-management-api-key
spec:
  secretStoreRef:
    kind: SecretStore
    name: doppler-heimdall-svc
  target:
    name: heimdall-svc-tyk-management-api-key
  data:
    - secretKey: TYK_MANAGEMENT_API_KEY
      remoteRef:
        key: TYK_MANAGEMENT_API_KEY
