---
# Source: deployment/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: heimdall-svc
  labels:
    helm.sh/chart: deployment-0.1.0
    app.kubernetes.io/name: heimdall-svc
    app.kubernetes.io/instance: heimdall-deployment
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: heimdall-svc
      app.kubernetes.io/instance: heimdall-deployment
  template:
    metadata:
      labels:
        helm.sh/chart: deployment-0.1.0
        app.kubernetes.io/name: heimdall-svc
        app.kubernetes.io/instance: heimdall-deployment
        app.kubernetes.io/managed-by: Helm
    spec:
      securityContext:
        {}
      containers:
        - name: heimdall-svc
          securityContext:
            {}
          image: "ewr.vultrcr.com/polytlk/heimdall:sha-be1405b"
          ports:
            - containerPort: 8000
              protocol: TCP
          env:
            - name: DJANGO_SECRET
              valueFrom:
                secretKeyRef:
                  key: DJANGO_SECRET
                  name: heimdall-svc-django-secret
            - name: ALLOWED_HOSTS
              value: heimdall-svc.heimdall.svc,localhost
            - name: SERVICE_NAME
              value: heimdall-service
            - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
              value: http://opentelemetry-collector.opentelemetry.svc.cluster.local/v1/traces
            - name: GATEWAY_HOST
              value: gateway-svc-tyk.tyk.svc.cluster.local
            - name: EDEN_API_ID
              value: ZWRlbi9lZGVuLWFwaQ
            - name: ENVIRONMENT
              value: development
            - name: GATEWAY_PORT
              value: "80"
          livenessProbe:
            httpGet:
              httpHeaders:
                - name: Host
                  value: heimdall-svc.heimdall.svc
              path: /healthz/
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              httpHeaders:
                - name: Host
                  value: heimdall-svc.heimdall.svc
              path: /readiness/
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
