global:
  components:
    operator: false
  redis:
    addrs:
    - vultr-prod-d47b69c5-e2a2-45ec-87e7-0ea500632c3e-vultr-prod-e0ea.vultrdb.com:16752
    passSecret:
      keyName: REDIS_PASS
      name: tyk-secrets-redis-pass
    storage:
      database: 0
    useSSL: true
  secrets:
    useSecretName: tyk-secrets-tyk-api-secret
  servicePorts:
    gateway: 80
operatorSecret:
  enabled: false
tyk-gateway:
  fullnameOverride: tyk
  gateway:
    containerPort: 8080
    extraEnvs:
    - name: TYK_GW_ENABLEJSVM
      value: "true"
    - name: TYK_GW_LOGLEVEL
      value: info
    - name: TYK_GW_POLICIES_POLICYSOURCE
      value: file
    - name: TYK_GW_POLICIES_POLICYPATH
      value: "/mnt/tyk-gateway/policies"
    - name: TYK_GW_POLICIES_POLICYRECORDNAME
      value: /mnt/tyk-gateway/policies/policies.json
    extraVolumeMounts:
    - mountPath: /mnt/tyk-gateway/policies
      name: policy-config
      readOnly: true
    - mountPath: /mnt/tyk-gateway/middleware
      name: sse-auth-pre-middleware
      readOnly: true
    extraVolumes:
    - configMap:
        name: policy-config
      name: policy-config
    - configMap:
        name: sse-auth-pre-middleware-tbmcf478cg
      name: sse-auth-pre-middleware
    hostName: tyk-gw.local
    image:
      repository: docker.tyk.io/tyk-gateway/tyk-gateway
      tag: v5.5.0
    ingress:
      annotations: {}
      className: nginx
      enabled: true
      hosts:
      - host: dev.api.polytlk.io
        paths:
        - backend:
            service:
              name: gateway-svc-tyk
              port:
                number: 80
          path: /
          pathType: Prefix
      tls:
      - hosts:
        - dev.api.polytlk.io
        secretName: tyk-secrets-tls-secret
    initContainers:
      setupDirectories:
        repository: busybox
        tag: 1.32
    kind: Deployment
    opentelemetry:
      connectionTimeout: 1
      contextPropagation: tracecontext
      enabled: true
      endpoint: http://opentelemetry-collector.opentelemetry.svc.cluster.local/v1/traces
      exporter: http
      headers: {}
      resourceName: tyk-api-gateway
      spanProcessorType: batch
    replicaCount: 1
