---
# Source: secret/templates/external-secret.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tyk-secrets-redis-pass
spec:
  secretStoreRef:
    kind: SecretStore
    name: doppler-tyk-secrets
  target:
    name: tyk-secrets-redis-pass
  data:
    - secretKey: REDIS_PASS
      remoteRef:
        key: REDIS_PASS
---
# Source: secret/templates/external-secret.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tyk-secrets-tyk-api-secret
spec:
  secretStoreRef:
    kind: SecretStore
    name: doppler-tyk-secrets
  target:
    name: tyk-secrets-tyk-api-secret
  data:
    - secretKey: APISecret
      remoteRef:
        key: TYK_API_SECRET
