---
# Source: secret/templates/tls-external-secret.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tyk-secrets-tls-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: doppler-tyk-secrets
  target:
    name: tyk-secrets-tls-secret
    template:
      type: kubernetes.io/tls
      data:
        tls.crt: "{{ .crt | fromJson | dig \"CERT\" . | b64dec }}"
        tls.key: "{{ .crt | fromJson | dig \"KEY\" .  | b64dec }}"
  data:
    - secretKey: crt
      remoteRef:
        key: TLS_CERT
