---
# Source: deployment/templates/external-secret.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: socrates-svc-openai-api-key
spec:
  secretStoreRef:
    kind: SecretStore
    name: doppler-socrates-svc
  target:
    name: socrates-svc-openai-api-key
  data:
    - secretKey: OPENAI_API_KEY
      remoteRef:
        key: OPENAI_API_KEY
