---
# Source: deployment/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-client-svc
  labels:
    helm.sh/chart: deployment-0.1.0
    app.kubernetes.io/name: web-client-svc
    app.kubernetes.io/instance: web-deployment
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: web-client-svc
      app.kubernetes.io/instance: web-deployment
  template:
    metadata:
      labels:
        helm.sh/chart: deployment-0.1.0
        app.kubernetes.io/name: web-client-svc
        app.kubernetes.io/instance: web-deployment
        app.kubernetes.io/managed-by: Helm
    spec:
      securityContext:
        {}
      containers:
        - name: web-client-svc
          securityContext:
            {}
          image: "ewr.vultrcr.com/polytlk/web-client:sha-0c8bb50"
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: BASE_URL
              value: https://dev.api.polytlk.io
            - name: TARGET_ENV
              value: development
            - name: CLIENT_ID_WEB
              value: 1048294563394-dk9or7n1rbindlioiq9esda80erktjkh.apps.googleusercontent.com
          volumeMounts:
            - mountPath: /etc/nginx/ssl
              name: web-client-svc-tls-secret
              readOnly: true
      volumes:
        - name: web-client-svc-tls-secret
          secret:
            secretName: web-client-svc-tls-secret
